import { MediaReview } from '../types';

export const loadReviews = async (): Promise<MediaReview[]> => {
  try {
    // In production, this file is generated by scripts/build-reviews.js
    const response = await fetch('/reviews.json');
    if (!response.ok) {
      console.warn("Could not load reviews.json. If you are in development, ensure you have run the build script.");
      return [];
    }
    const data = await response.json();
    return data;
  } catch (e) {
    console.error("Error loading reviews:", e);
    return [];
  }
};

export const downloadReviewYaml = (review: MediaReview) => {
  // Helper to sanitize strings for YAML quotes
  const safeString = (str: string) => str ? str.replace(/"/g, '\\"') : '';

  // Check if the ID is a temporary UUID (new review) or a filename slug (existing review)
  // UUID regex: 8-4-4-4-12 hex digits
  const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(review.id);

  // If it's an existing review (slug), keep the filename.
  // If it's new (UUID), generate filename from title.
  const filenameSlug = (!isUuid && review.id)
    ? review.id
    : review.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

  // Manually construct YAML string to avoid browser dependencies
  // Note: We DO NOT include the 'id' field in the YAML, as it is determined by filename
  let yamlContent = '';
  yamlContent += `title: "${safeString(review.title)}"\n`;
  yamlContent += `type: "${review.type}"\n`;
  if (review.author) yamlContent += `author: "${safeString(review.author)}"\n`;
  yamlContent += `rating: ${review.rating}\n`;
  yamlContent += `releaseYear: ${review.releaseYear}\n`;
  yamlContent += `reviewDate: "${review.reviewDate}"\n`;
  if (review.updatedDate) yamlContent += `updatedDate: "${review.updatedDate}"\n`;

  yamlContent += `text:\n`;
  review.text.forEach(point => {
    yamlContent += `  - |\n`;
    const lines = point.split('\n');
    lines.forEach(line => {
      yamlContent += `    ${line}\n`;
    });
  });

  // Trigger download
  const blob = new Blob([yamlContent], { type: 'text/yaml' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filenameSlug}.yaml`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};